# -*- coding: utf-8 -*-
"""GeradorSMILES_SilhuetaATUAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jeXpB71QfY0enCgxVFOS6qCj0-7uU8ne
"""

!pip install rdkit

import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
from google.colab import drive

#drive.mount('/content/drive') ##OPCIONAL, APENAS PARA MODIFICAR BANCOS JÁ TERMINADOS

"""# Etapa 1: Separar as listas de componentes Aneis, Pontes, Auxocromos e Linhas"""

ABCKeys3GenAneisSMILES = {
    1: ('c1cccc1'),
    2: ('C1CCCCC1'),
    3: ('N1CCCCC1'),
    4: ('O1CCCCC1'),
    5: ('S1CCCCC1'),
    6: ('B1CCCCC1'),
    7: ('C1CCOCC1'),
    8: ('C1COCCC1'),
    9: ('C1OCCCC1'),
    10: ('C1CCNCC1'),
    11: ('C1CNCCC1'),
    12: ('C1NCCCC1'),
    13: ('C1CCSCC1'),
    14: ('C1CSCCC1'),
    15: ('C1SCCCC1'),
    16: ('N1CCNCC1'),
    17: ('N1CCOCC1'),
    18: ('N1CCSCC1'),
    19: ('O1CCOCC1'),
    20: ('O1CCSCC1'),
    21: ('S1CCSCC1'),
    22: ('c1cccc1'),
    23: ('C1CCCC1'),
    24: ('N1CCCC1'),
    25: ('O1CCCC1'),
    26: ('S1CCCC1'),
    27: ('N1NCCC1'),
    28: ('O1NCCC1'),
    29: ('S1NCCC1'),
    30: ('N1CNCC1'),
    31: ('O1CNCC1'),
    32: ('S1CNCC1'),
    33: ('C1CSCC1'),
    34: ('C1NCCC1'),
    35: ('C1CNCC1'),
    36: ('C1OCCC1'),
    37: ('C1COCC1'),
    38: ('C1SCCC1'),
    39: ('O1COCCC1'),
    40: ('O1OCCCC1'),
    41: ('O1NCCCC1'),
    42: ('O1SCCCC1'),
    43: ('N1NCCCC1'),
    44: ('N1SCCCC1'),
    45: ('S1SCCCC1'),
    46: ('O1CNCCC1'),
    47: ('O1CSCCC1'),
    48: ('S1CSCC1'),
    49: ('N1ONCC1')
}

ABCKeys4GenAneisSMILES = {
   0: ('C1SS1'),
1: ('C1OO1'),
2: ('C1NN1'),
3: ('C1OS1'),
4: ('C1CO1'),
5: ('N1NN1'),
6: ('N1SS1'),
7: ('N1:S:S:1'),
8: ('C1NO1'),
9: ('C1COO1'),
10: ('C1NNN1'),
11: ('C1CNN1'),
12: ('C1CSS1'),
13: ('C1CCC1'),
14: ('C1COS1'),
15: ('C1:C:N:N:1'),
16: ('C1:C:C:C:1'),
17: ('C1CCN1'),
18: ('O1OOO1'),
19: ('N1NSS1'),
20: ('C1SSS1'),
21: ('C1CCP1'),
22: ('C1CCO1'),
23: ('C1PSS1'),
24: ('C1:C:S:S:1'),
25: ('C1:C:C:O:1'),
26: ('P1PSS1'),
27: ('C1CNS1'),
28: ('C1OOO1'),
29: ('C1CNO1'),
30: ('P1PPP1'),
31: ('O1OOP1'),
32: ('C1CCNN1'),
33: ('C1:C:C:C:N:1'),
34: ('C1:C:C:N:N:1'),
35: ('C1:C:C:C:C:1'),
36: ('C1:C:C:C:S:1'),
37: ('C1CCSS1'),
38: ('C1:N:N:N:N:1'),
39: ('C1:C:N:N:S:1'),
40: ('C1:C:C:C:O:1'),
41: ('C1:C:C:N:O:1'),
42: ('C1:C:C:N:S:1'),
43: ('C1:C:C:C:P:1'),
44: ('C1:C:N:N:N:1'),
45: ('C1NNNN1'),
46: ('C1CNSS1'),
47: ('C1NOOS1'),
48: ('C1CNNP1'),
49: ('C1CCNO1'),
50: ('C1CCCN1'),
51: ('C1CCCP1'),
52: ('C1CCCCC1'),
53: ('C1CCCCN1'),
54: ('C1CCCNN1'),
55: ('C1CCCCO1'),
56: ('C1CCCNO1'),
57: ('C1CCCNS1'),
58: ('C1CCNNO1'),
59: ('C1CCNNS1'),
60: ('C1CCNOO1'),
61: ('C1CNNNN1'),
62: ('C1CNNNS1'),
63: ('C1NNNNN1'),
64: ('C1:C:C:C:C:C:1'),
65: ('C1:C:C:C:C:N:1'),
66: ('C1:C:C:C:C:O:1'),
67: ('C1:C:C:C:N:N:1'),
68: ('C1:C:C:C:C:C:C:1'),
69: ('C1CCCCNN1'),
70: ('C1CCCNNN1'),
71: ('C1CCCCNS1'),
72: ('C1CCCCCC1'),
73: ('C1CCCNNS1'),
74: ('C1CCCCSS1'),
75: ('C1CCNNNN1'),
76: ('C1CCCCCN1'),
77: ('C1CCCCOO1'),
78: ('C1CCCNNO1'),
79: ('C1CCCOOO1'),
80: ('C1CCCCOS1'),
81: ('C1CCCCCO1'),
82: ('C1CCCCNO1'),
83: ('C1CCCCCP1'),
84: ('C1CCCOOP1'),
85: ('C1CCCCCS1'),
86: ('C1CCSSSS1'),
87: ('C1CNNSSS1'),
88: ('C1CSSSSS1'),
89: ('C1CCNNNS1'),
90: ('C1:C:C:C:C:N:N:1'),
91: ('C1:C:C:C:C:C:P:1'),
92: ('C1:C:C:C:C:C:N:1'),
93: ('C1:C:C:C:N:N:S:1'),
94: ('C1:C:C:C:O:O:P:1'),
95: ('C1:C:C:C:N:N:N:1'),
96: ('C1:C:C:C:C:C:O:1'),
97: ('C1:C:N:N:S:S:S:1'),
98: ('C1CCCCCOS1'),
99: ('C1CCCCCNN1'),
100: ('C1CCCCCCO1'),
101: ('C1CCCCCCC1'),
102: ('C1CCCCCOO1'),
103: ('C1CCCCCCN1'),
104: ('C1CCCCOOS1'),
105: ('C1CCCCOOO1'),
106: ('C1CCCCCCS1'),
107: ('C1CCCNNNN1'),
108: ('C1CCCCSSS1'),
109: ('C1CCCCNSS1'),
110: ('C1CCCCNNN1'),
111: ('C1CCNNNNN1'),
112: ('C1CCNNNNN1'),
113: ('C1CCCCCNS1'),
114: ('C1CCCCNNS1'),
115: ('C1CCCCCNO1'),
116: ('C1CCCNOOS1'),
117: ('C1CCSSSSS1'),
118: ('C1:C:C:C:C:C:N:N:1'),
119: ('C1:C:C:C:C:C:O:S:1'),
120: ('C1:C:C:C:C:C:O:O:1'),
121: ('C1:C:C:C:C:C:C:O:1'),
122: ('C1:C:C:C:C:C:N:O:1'),
123: ('C1:C:C:C:C:N:S:S:1'),
124: ('C1:C:C:C:N:N:N:N:1'),
125: ('C1:C:C:N:N:N:N:N:1')
}

#ABCKeys3GenPontesSMILES = {
 #   1: ('N=N')}

ABCKeys3GenPontesSMILES = {
    1: ('N=N'),
    2: ('C=CC(=O)'),
    3: ('C=CC(=O)CC(=O)C=C'),
    4: ('C=C'),
    5: ('N='),
    6: ('C='),
    7: ('C=N'),
    8: ('=CC='),
    9: ('-'),
    10: ('='),
    11: ('C#C'),
    12: ('C#CC#C'),
    13: ('C=CC=C'),
    14: ('O'),
    15: ('C=CC=CC'),
    16: ('C=CC=CC=C'),
    17: ('C=CC=CC=CC=C'),
    18: ('NC'),
    19: ('C(=N)'),
    20: ('C=C(C)C=C')
}

ABCKeys3GenFragsSMILES = {
    1: ('N(C)C'),
    2: ('S(=O)=O'),
    3: ('C'),
    4: ('CC'),
    5: ('Cl'),
    6: ('[N+](=O)O'),
    7: ('OC'),
    8: ('N=O'),
    9: ('N(CC)CC'),
    10: ('S(=O)(=O)[O][Na]'),
    11: ('N'),
    12: ('O'),
    13: ('NC(=O)C'),
    14: ('C(=O)O'),
    15: ('=C(C#N)C#N'),
    16: ('CN(CC(=O)O)CC(=O)O'),
    17: ('C(F)(F)F'),
    18: ('C(=O)OCC'),
    19: ('C(=O)[O][Na]'),
    20: ('[O][Na]'),
    21: ('Br'),
    22: ('S(=O)(=O)O'),
    23: ('NCC'),
    24: ('C(C)C'),
    25: ('=N'),
    26: ('=O')
}

#ABCKeys3GenFragsSMILES = {
#   1: ('N=O')
#}

ABCKeys4GenLinhaSMILES = {
    1: ('C-C'),
    2: ('C=C'),
    3: ('C-N'),
    4: ('C=N'),
    5: ('C-O'),
    6: ('C=O'),
    7: ('N=O'),
    8: ('C=C-O'),
    9: ('C-C=O'),
    10: ('C-C-O'),
    11: ('C-C-C'),
    12: ('C-N=O'),
    13: ('C=N-O'),
    14: ('O=N-O'),
    15: ('C-C-C-C'),
    16: ('C-C=C-C'),
    17: ('O=C-C=O'),
    18: ('C=C-C=O'),
    19: ('C-C=S'),
    20: ('C=C-C-C'),
    21: ('N-N=O'),
    22: ('O=C-O'),
    23: ('N-N=O'),
    24: ('C-N-C'),
    25: ('C=C-F'),
    26: ('C=C-C'),
    27: ('N-C=O'),
    28: ('C=C-C=C'),
    29: ('C=C-C-C'),
    30: ('C-C-C-O'),
    31: ('C=F-F-P'),
    32: ('C-C-C=O'),
    33: ('C-C-N-C'),
    34: ('C-C-O-C'),
    35: ('C-C-C-N'),
    36: ('N-C=O'),
    37: ('C-C-N'),
    38: ('C=N=N'),
    39: ('C=C-N'),
    40: ('N=N'),
    41: ('C-O-C'),
    42: ('C=N=N'),
    43: ('C-S'),
    44: ('N-C=S'),
    45: ('C=C-C-O'),
    46: ('C-C=C-N'),
    47: ('C=C-C-O'),
    48: ('C-N-N=O'),
    49: ('C-O-C=O'),
    50: ('C-N-C=O'),
    51: ('N=C-C=O'),
    52: ('N-C-C-N'),
    53: ('N-C=S'),
    54: ('C-C=N'),
    55: ('C=C-O'),
    56: ('N-N'),
    57: ('C-C=C-O'),
    58: ('C-N-N=O'),
    59: ('C-C-N-O'),
    60: ('N-C-C-O'),
    61: ('O=C-C-O')
}

"""# Função para fundir anéis com auxocromos
 ## posicoes = random.sample(posicoes_possiveis, n) define o número de auxocromos
"""

import random

# ------------------------------------------------------------
# Função para inserir um fragmento em uma posição específica do SMILES
# ------------------------------------------------------------
def inserir_fragmento(smiles: str, pos: int, frag: str) -> str:
    """
    Insere o fragmento frag na posição pos do SMILES smiles.
    """
    pos = max(0, min(pos, len(smiles)))  # garante que a posição seja válida
    return smiles[:pos] + f"({frag})" + smiles[pos:]

# ------------------------------------------------------------
# Função para gerar um SMILES modificado com 3 fragmentos aleatórios
# ------------------------------------------------------------
def gerar_smiles_modificado(smiles_base: str, frags_dict: dict) -> str:
    """
    Gera um SMILES a partir do smiles_base inserindo 3 fragmentos aleatórios
    em posições distintas.
    """
    smiles_mod = smiles_base
    posicoes_possiveis = [2, 3, 4, 5, 6] #### Define a posição dos Auxocromos
    quantia_possivel = 3 #Número de Substituintes

    # Escolhe 3 posições distintas
    posicoes = random.sample(posicoes_possiveis, quantia_possivel) #### Define a quantidade de auxocromos por anel

    # Prepara lista de inserções (posição, fragmento)
    insercoes = [(pos, frags_dict[random.randint(1, 1)]) for pos in posicoes]

    # Ordena em ordem decrescente para não deslocar posições
    insercoes.sort(key=lambda x: x[0], reverse=True)

    # Insere os fragmentos
    for pos, frag in insercoes:
        smiles_mod = inserir_fragmento(smiles_mod, pos, frag)

    return smiles_mod

# ------------------------------------------------------------
# Função para gerar múltiplos SMILES modificados para todos os anéis
# ------------------------------------------------------------
def gerar_todos(aneis_dict: dict, frags_dict: dict, repeticoes: int = 10) -> dict:
    """
    Para cada anel no dicionário aneis_dict, gera repeticoes SMILES modificados.
    """
    resultado_final = {}
    counter = 1

    for key_anel, smiles_base in aneis_dict.items():
        for _ in range(repeticoes):
            smiles_gerado = gerar_smiles_modificado(smiles_base, frags_dict)
            resultado_final[counter] = smiles_gerado
            counter += 1

    return resultado_final

# ------------------------------------------------------------
# Função auxiliar que insere fragmentos seguindo instruções específicas
# ------------------------------------------------------------
def inserir_fragmentos_dict(dict_aneis: dict, dict_frags: dict, key_anel: int, instrucoes: list) -> str:
    """
    Insere fragmentos em um SMILES base seguindo instruções.

    instrucoes: lista de tuplas (posição, key_fragmento)
    """
    base = dict_aneis[key_anel]
    resultado = base
    deslocamento = 0

    # Ordena instruções por posição
    for pos, frag_key in sorted(instrucoes, key=lambda x: x[0]):
        frag = dict_frags[frag_key]
        inserir = f"({frag})"
        pos_real = pos + deslocamento
        resultado = resultado[:pos_real + 1] + inserir + resultado[pos_real + 1:]
        deslocamento += len(inserir)

    return resultado

from rdkit import Chem

# ------------------------------------------------------------
def dict_para_df_validado(smiles_dict: dict) -> pd.DataFrame:
    """
    Recebe um dicionário {id: smiles} e retorna um DataFrame
    com apenas SMILES válidos.
    """
    resultados = []
    for idx, smiles in smiles_dict.items():
        # Validação do SMILES
        if Chem.MolFromSmiles(smiles) is not None:
            resultados.append({"id": idx, "smiles": smiles})

    df = pd.DataFrame(resultados)
    return df

# ------------------------------------------------------------
# Exemplo de uso com sua função gerar_todos
# ------------------------------------------------------------
resultado = gerar_todos(ABCKeys3GenAneisSMILES, ABCKeys3GenFragsSMILES, repeticoes=200)
df300 = dict_para_df_validado(resultado)

print(len(df))
df.head(1000)

"""# Etapa de eliminação de Duplicatas de Anéis com Auxocromos"""

from rdkit import Chem
import pandas as pd

def remover_duplicatas_rdkit(df: pd.DataFrame, coluna_smiles: str = "smiles") -> pd.DataFrame:
    """
    Remove duplicatas de moléculas equivalentes no DataFrame usando RDKit.

    Parâmetros:
    - df: DataFrame com uma coluna de SMILES
    - coluna_smiles: nome da coluna que contém os SMILES

    Retorna:
    - DataFrame sem moléculas duplicadas
    """
    seen_mols = set()
    indices_para_manter = []

    for idx, smi in df[coluna_smiles].items():
        mol = Chem.MolFromSmiles(smi)
        if mol is None:
            continue  # ignora SMILES inválidos
        # Canonical SMILES para identificação única
        can_smi = Chem.MolToSmiles(mol, canonical=True)
        if can_smi not in seen_mols:
            seen_mols.add(can_smi)
            indices_para_manter.append(idx)

    # Retorna apenas as linhas com moléculas únicas
    return df.loc[indices_para_manter].reset_index(drop=True)

# ------------------------------------------------------------
# Exemplo de uso
# ------------------------------------------------------------
df = remover_duplicatas_rdkit(df, coluna_smiles="smiles")

"""#MONTAGEM DOS SMILES COMPLEXOS"""

import numpy as np
import pandas as pd
from rdkit import Chem

def gerar_combinacoes_otimizado(df100, df2, pontes_dict, n_total=10_000, batch=200_000):
    # Copias para segurança
    df = df.copy()
    df2 = df.copy()

    # ============================
    # 1) Filtra apenas moléculas válidas
    # ============================
    df["mol"] = df["smiles"].apply(Chem.MolFromSmiles)
    df = df[df["mol"].notna()]

    df2["mol"] = df2["smiles"].apply(Chem.MolFromSmiles)
    df2 = df2[df2["mol"].notna()]

    smiles1 = df["smiles"].to_numpy(dtype=object)
    smiles2_raw = df2["smiles"].to_numpy(dtype=object)

    # ============================
    # 2) Pré-conversão leve: troca '1' → '2' no segundo DF
    # ============================
    # Usa np.vectorize (mais leve que list comprehension para grandes arrays)
    trocar = np.vectorize(lambda s: s.replace("1", "2"))
    smiles2_mod = trocar(smiles2_raw)

    # ============================
    # 3) Pontes como array
    # ============================
    pontes = np.array([v[0] for v in pontes_dict.values()], dtype=object)

    n1 = len(smiles1)
    n2 = len(smiles2_mod)
    npontes = len(pontes)

    seen = set()
    resultados = []

    # ============================
    # 4) Loop principal (mínimo overhead)
    # ============================
    while len(seen) < n_total:

        # ----------------------------
        # GERAÇÃO TOTALMENTE VETORIZADA
        # ----------------------------
        idx1 = np.random.randint(0, n1, batch)
        idx2 = np.random.randint(0, n2, batch)
        idxp = np.random.randint(0, npontes, batch)

        # concatenação 100% numpy (rápida!)
        candidatos = smiles1[idx1] + pontes[idxp] + smiles2_mod[idx2]

        # ----------------------------
        # VALIDAÇÃO RDKit
        # ----------------------------
        for s in candidatos:
            mol = Chem.MolFromSmiles(s)
            if mol is None:
                continue

            can = Chem.MolToSmiles(mol, canonical=False)

            if can not in seen:
                seen.add(can)
                resultados.append(can)

                if len(seen) >= n_total:
                    break

    return pd.DataFrame({"smiles": resultados})

df_11 = gerar_combinacoes_otimizado(df, df2,  ABCKeys3GenPontesSMILES)
print(df_11.head())
print(len(df_11))

"""# Criação de Duplicata dos SMILES Saturados desenvolvidos"""

from rdkit import Chem
import pandas as pd

def aromatizar_aneis_seis_membros(smiles):
    """
    Tenta aromatizar todos os anéis de 6 membros.
    Retorna o SMILES aromatizado ou None se falhar.
    """
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None

    # Identifica anéis
    ri = mol.GetRingInfo()
    atom_rings = ri.AtomRings()

    # Para cada anel, se tiver 6 membros, tenta aromatizar
    for ring in atom_rings:
        if len(ring) == 6:
            # Tenta marcar ligações como aromáticas
            for i in range(len(ring)):
                a1 = ring[i]
                a2 = ring[(i + 1) % len(ring)]
                bond = mol.GetBondBetweenAtoms(a1, a2)
                if bond is None:
                    return None
                bond.SetBondType(Chem.rdchem.BondType.AROMATIC)

            # Marca átomos como aromáticos
            for idx in ring:
                atom = mol.GetAtomWithIdx(idx)
                atom.SetIsAromatic(True)

    # Sanitiza e verifica se é válido
    try:
        Chem.SanitizeMol(mol)
    except:
        return None

    return Chem.MolToSmiles(mol)

# --------------------------
# EXEMPLO DE USO
# --------------------------


# Cria o novo df:
df_11["aroma"] = df_11["smiles"].apply(aromatizar_aneis_seis_membros)

# Remove inválidos
df_validos = df_11.dropna(subset=["aroma"]).reset_index(drop=True)
df_validos.drop(columns=["smiles"], inplace=True)

df_validos.to_parquet("INSIRA_NOME.parquet", index=False) #####Definir nome para a ocasião

print(f"Mantidas {len(df_validos)} moléculas aromatizáveis.")

"""# FILTRAGEM DOS AROMÁTICOS INVÁLIDOS"""

import pandas as pd
from rdkit import Chem

def filtrar_aromaticos_validos(df):
    df = df_11.copy()

    def is_valid(smiles):
        mol = Chem.MolFromSmiles(smiles)
        return mol is not None

    # Filtra apenas os válidos
    df_filtrado = df[df['aroma'].apply(is_valid)].reset_index(drop=True)

    print("Tamanho final do DF:", len(df_filtrado))
    return df_filtrado

df_filtrado = filtrar_aromaticos_validos(df_11)

print(len(df_filtrado))
df_filtrado.head(1000)

df_filtrado.to_parquet("Banco_APA(1_2S_AROM_filtrado).parquet")