AUXOCROMOS: dict[int, str] = {
    1:  "N(C)C",
    2:  "S(=O)=O",
    3:  "C",
    4:  "CC",
    5:  "Cl",
    6:  "[N+](=O)O",
    7:  "OC",
    8:  "N=O",
    9:  "N(CC)CC",
    10: "S(=O)(=O)[O][Na]",
    11: "N",
    12: "O",
    13: "NC(=O)C",
    14: "C(=O)O",
    15: "=C(C#N)C#N",
    16: "CN(CC(=O)O)CC(=O)O",
    17: "C(F)(F)F",
    18: "C(=O)OCC",
    19: "C(=O)[O][Na]",
    20: "[O][Na]",
    21: "Br",
    22: "S(=O)(=O)O",
    23: "NCC",
    24: "C(C)C",
    25: "=N",
    26: "=O",
}