PONTES: dict[int, str] = {
    1:  "N=N",
    2:  "C=CC(=O)",
    3:  "C=CC(=O)CC(=O)C=C",
    4:  "C=C",
    5:  "N=",
    6:  "C=",
    7:  "C=N",
    8:  "=CC=",
    9:  "-",
    10: "=",
    11: "C#C",
    12: "C#CC#C",
    13: "C=CC=C",
    14: "O",
    15: "C=CC=CC",
    16: "C=CC=CC=C",
    17: "C=CC=CC=CC=C",
    18: "NC",
    19: "C(=N)",
    20: "C=C(C)C=C",
}